require_relative 'mimsy/acqitems'
require_relative 'mimsy/acquisition'
require_relative 'mimsy/acquisition_sources'
require_relative 'mimsy/cat'
require_relative 'mimsy/disposal_sources'
require_relative 'mimsy/inscription'
require_relative 'mimsy/item_names'
require_relative 'mimsy/items_makers'
require_relative 'mimsy/items_people_sources'
require_relative 'mimsy/locations'
require_relative 'mimsy/measurements'
require_relative 'mimsy/notepad'
require_relative 'mimsy/people'
require_relative 'mimsy/place'
require_relative 'mimsy/related_item'
require_relative 'mimsy/source_details'
require_relative 'mimsy/subject'

module Mimsy
end
